//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTaxes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesTaxes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------.
        /// </summary>
        internal static string separator {
            get {
                return ResourceManager.GetString("separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added in basket.
        /// </summary>
        internal static string txt_addedInBasket {
            get {
                return ResourceManager.GetString("txt_addedInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the next information for the new product.
        /// </summary>
        internal static string txt_addNewProduct {
            get {
                return ResourceManager.GetString("txt_addNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product.
        /// </summary>
        internal static string txt_addProduct {
            get {
                return ResourceManager.GetString("txt_addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string txt_at {
            get {
                return ResourceManager.GetString("txt_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return? Your current basket will be lost..
        /// </summary>
        internal static string txt_backToMainMenu {
            get {
                return ResourceManager.GetString("txt_backToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic tax.
        /// </summary>
        internal static string txt_basicTax {
            get {
                return ResourceManager.GetString("txt_basicTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string txt_category {
            get {
                return ResourceManager.GetString("txt_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify any information of an existing product.
        /// </summary>
        internal static string txt_editExistingProduct {
            get {
                return ResourceManager.GetString("txt_editExistingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        internal static string txt_editProduct {
            get {
                return ResourceManager.GetString("txt_editProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string txt_exit {
            get {
                return ResourceManager.GetString("txt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is imported?.
        /// </summary>
        internal static string txt_import {
            get {
                return ResourceManager.GetString("txt_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tax.
        /// </summary>
        internal static string txt_importTax {
            get {
                return ResourceManager.GetString("txt_importTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of products.
        /// </summary>
        internal static string txt_listOfProducts {
            get {
                return ResourceManager.GetString("txt_listOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string txt_name {
            get {
                return ResourceManager.GetString("txt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products in basket.
        /// </summary>
        internal static string txt_noProducts {
            get {
                return ResourceManager.GetString("txt_noProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add products to your basket.
        /// </summary>
        internal static string txt_pickProducts {
            get {
                return ResourceManager.GetString("txt_pickProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key to exit....
        /// </summary>
        internal static string txt_pressAKey {
            get {
                return ResourceManager.GetString("txt_pressAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string txt_price {
            get {
                return ResourceManager.GetString("txt_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string txt_purchase {
            get {
                return ResourceManager.GetString("txt_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return....
        /// </summary>
        internal static string txt_return {
            get {
                return ResourceManager.GetString("txt_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        internal static string txt_steps {
            get {
                return ResourceManager.GetString("txt_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string txt_validation_name {
            get {
                return ResourceManager.GetString("txt_validation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What property you would like to modify?.
        /// </summary>
        internal static string txt_whatEdit {
            get {
                return ResourceManager.GetString("txt_whatEdit", resourceCulture);
            }
        }
    }
}
